export const ARTICLES_ACTION_TYPES = {
    SET_ARTICLES_START: 'articles/SET_ARTICLES_START',
    SET_ARTICLES_SUCCESS: 'articles/SET_ARTICLES_SUCCESS',
    SET_ARTICLES_FAILURE: 'articles/SET_ARTICLES_FAILURE',

    FETCH_ARTICLES_START: 'articles/FETCH_ARTICLES_START',
    FETCH_ARTICLES_SUCCESS: 'articles/FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLES_FAILURE: 'articles/FETCH_ARTICLES_FAILURE',

    SET_ARTICLES_SEARCHED_START: 'articles/SET_ARTICLES_SEARCHED_START',
    SET_ARTICLES_SEARCHED_SUCCESS: 'articles/SET_ARTICLES_SEARCHED_SUCCESS',
    SET_ARTICLES_SEARCHED_FAILURE: 'articles/SET_ARTICLES_FAILURE',

}